import { AuthProvider } from "@/components/AuthProvider";
import { Nav } from "@/components/Nav";
import {
  cachedGetAuthenticatedAppForUser,
  getBearerToken,
} from "@/lib/firebase/serverApp";
import { User } from "firebase/auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { currentUser } =
    await cachedGetAuthenticatedAppForUser(getBearerToken());
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider initialUser={currentUser?.toJSON() as User}>
          <main className="container mx-auto p-2">
            <Nav />
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
